### ISSUE TITLE
When I cmake the project ,there is a problem

### ISSUE THREAD

**Issue by smallsnailrunning** [YongyuG/rnnoise_16k#1]
![1587547866(1)](https://user-images.githubusercontent.com/43053983/79965944-45081900-84bf-11ea-9642-90616c57135f.jpg)

the second problem is :

if I want to train my data ,in the run.sh,I need prepared a speech.wav  and a noise.wav ,but,in the  run.sh,mixed.wav, need I prepare ? Or,it will auto generate?

**Comment by YongyuG** [comment]
> ![1587547866(1)](https://user-images.githubusercontent.com/43053983/79965944-45081900-84bf-11ea-9642-90616c57135f.jpg)
> 
> the second problem is :
> 
> if I want to train my data ,in the run.sh,I need prepared a speech.wav and a noise.wav ,but,in the run.sh,mixed.wav, need I prepare ? Or,it will auto generate?

HI , I have updated the code, the compiling mistake is solved, you can pull it and recompile, I think it works fine now. 

For your second question, you need to prepare two folder which called speech and noise, and the mixed.wav is auto generated.

**Comment by YongyuG** [comment]
> ![1587547866(1)](https://user-images.githubusercontent.com/43053983/79965944-45081900-84bf-11ea-9642-90616c57135f.jpg)
> 
> the second problem is :
> 
> if I want to train my data ,in the run.sh,I need prepared a speech.wav and a noise.wav ,but,in the run.sh,mixed.wav, need I prepare ? Or,it will auto generate?

I have uploaded a compiled binary in **./bin**, you can try to use it although it trained in Chinese speech

**Comment by WangQin-wq** [comment]
How to test the noisy audio after the training here is completed?I think 48ks can be directly put into the I/O file in the file rnnoise_demo. What is the command 16k? I hope you can answer it

**Comment by YongyuG** [comment]
> How to test the noisy audio after the training here is completed?I think 48ks can be directly put into the I/O file in the file rnnoise_demo. What is the command 16k? I hope you can answer it

check the CMaList.txt carefully, binary file will be generated, and the way to use this binary file is same as original one

**Comment by YongyuG** [comment]
老哥，你好好看cmake 呀．．．会有个可执行文件出来的．．．

________________________________
发件人: WangQin-wq ***@***.***>
发送时间: 2021年5月27日 3:33
收件人: YongyuG/rnnoise_16k ***@***.***>
抄送: Yongyu Gao ***@***.***>; Comment ***@***.***>
主题: Re: [YongyuG/rnnoise_16k] When I cmake the project ,there is a problem (#1)


想问下这边已经训练完成，如何对测试含噪音频进行降噪呢？我看48ks是在rnnoise_demo那个文件直接放入输入输出文件即可，16k这个命令是什么，希望您能解答下！！！

―
