### ISSUE TITLE
How to change the count？

### ISSUE THREAD

**Issue by april-lai** [YongyuG/rnnoise_16k#10]
hello，I want to know how to change the count of 80000000？because when I just want to try to train the model，the feature extracting costed a lot of time. Hope you can answer it，thank you very much！

**Comment by WangQin-wq** [comment]
I use denoise16.c to generate denoise files, and this problem occurs when extracting features:
![image](https://user-images.githubusercontent.com/68885523/119947432-4eb95580-bfca-11eb-85d3-6b4b970758ed.png)
I would like to ask why this feature matrix dimension can't be printed 50000*75, but the given size/75 *75 should be used. I hope the author can answer it. Thank you!

**Comment by YongyuG** [comment]
> hello，I want to know how to change the count of 80000000？because when I just want to try to train the model，the feature extracting costed a lot of time. Hope you can answer it，thank you very much！
80000000 means　80000000 frames for training,
if you wanna change this parameter, you can go to denoise.c, change it in main function.
` while (1) {
    kiss_fft_cpx X[FREQ_SIZE], Y[FREQ_SIZE], N[FREQ_SIZE], P[WINDOW_SIZE];
    float Ex[NB_BANDS], Ey[NB_BANDS], En[NB_BANDS], Ep[NB_BANDS];
    float Exp[NB_BANDS];
    float Ln[NB_BANDS];
    float features[NB_FEATURES];
    float g[NB_BANDS];
    float gf[FREQ_SIZE]={1};
    short tmp[FRAME_SIZE];
    float vad=0;
    float vad_prob;
    float E=0;
    //if (count==5000) break;
//    if (count==50000000) break;
    if (count==50000) break;
  	fprintf(stderr, "count ===== %d \n", count);
    if (++gain_change_count > 2821) {
      speech_gain = pow(10., (-40+(rand()%60))/20.);
      noise_gain = pow(10., (-30+(rand()%50))/20.);`

**Comment by YongyuG** [comment]
> hello，I want to know how to change the count of 80000000？because when I just want to try to train the model，the feature extracting costed a lot of time. Hope you can answer it，thank you very much！

Count of 80000000 means you select 80000000 frames for training, which I dont think its a good idea to do, but anyway, the original author use this way.
Change this param  in denoise.c, main function... 
just remember, this whole c++ things is to do features extractions

**Comment by YongyuG** [comment]
> I use denoise16.c to generate denoise files, and this problem occurs when extracting features:
> ![image](https://user-images.githubusercontent.com/68885523/119947432-4eb95580-bfca-11eb-85d3-6b4b970758ed.png)
> I would like to ask why this feature matrix dimension can't be printed 50000*75, but the given size/75 *75 should be used. I hope the author can answer it. Thank you!

dont use denoise16k.c use denoise.c
