### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by LXP-Never** [YongyuG/rnnoise_16k#13]
1、src/compile.sh
2、../src/denoise_training ./data/clean ./data/noise ./mixed.wav > training_16k_v3.f32
然后报了Floating point exception (core dumped)的错误，我没改动代码

**Comment by YongyuG** [comment]
> 1、src/compile.sh 2、../src/denoise_training ./data/clean ./data/noise ./mixed.wav > training_16k_v3.f32 然后报了Floating point exception (core dumped)的错误，我没改动代码

有可能是你编译器版本的原因.高版本的gcc在链接时采用了新的哈希技术来提高动态链接的速度，这在低版本中是不支 持的。因此会发生这个错误。gcc就是一个编译器。编译出来的软件在低版本操作系统上有些技术不支持造成这个原因。我自己试的是没啥问题的...

**Comment by LXP-Never** [comment]
> > 1、src/compile.sh 2、../src/denoise_training ./data/clean ./data/noise ./mixed.wav > training_16k_v3.f32 然后报了Floating point exception (core dumped)的错误，我没改动代码
> 
> 有可能是你编译器版本的原因。高版本的gcc在链接时采用了新版本的中技术来提高动态链接的速度，在低端。因此会发生这个错误。gcc就是一个编译器。编译出来的软件在低版本上造成的，自己的技术不支持这个原因。我自己尝试的不是啥问题...

好的，谢啦，我将试试其他方法

**Comment by YongyuG** [comment]
> > > 1、src/compile.sh 2、../src/denoise_training ./data/clean ./data/noise ./mixed.wav > training_16k_v3.f32 然后报了Floating point exception (core dumped)的错误，我没改动代码
> > 
> > 
> > 有可能是你编译器版本的原因。高版本的gcc在链接时采用了新版本的中技术来提高动态链接的速度，在低端。因此会发生这个错误。gcc就是一个编译器。编译出来的软件在低版本上造成的，自己的技术不支持这个原因。我自己尝试的不是啥问题...
> 
> 好的，谢啦，我将试试其他方法

恩 你可以换个gcc版本试试看，反正多装几个gcc没问题的，软链一下就可以切换用
