### ISSUE TITLE
Is the performance of 16K model better 

### ISSUE THREAD

**Issue by shilsircar** [YongyuG/rnnoise_16k#2]
Wondering if you achieved better results with 16 Khz models compared to the original 46Khz models ?

**Comment by YongyuG** [comment]
> Wondering if you achieved better results with 16 Khz models compared to the original 46Khz models ?

of course, if you are going to use pre-trained 48K model to inference 16K audio, it need to resample the audio, 16K audios donot have info in 8k-24k freq band, which cannot perform as good as 16k model.

So using 16K model for 16K audio can do better denoise job.

Perhaps, you can try to train 16k model and compare it with 48k pre-trained one in PESQ or SDR to see the difference is more straightforward
