### ISSUE TITLE
source code for denoise_training_gao bin 

### ISSUE THREAD

**Issue by minchaoyue** [YongyuG/rnnoise_16k#4]
could you provide source code for denoise_training_gao?
 I want to retrain this mode with new data.

**Comment by sporwar-lifesize** [comment]
Is the denoise_gao.c file under bakcup2 the source for denoise_training_gao? Also, the count of the default denoise_training_gao is 80000000 x 75. Appreciate it if you could commit the denoise.c used for training. Thanks

**Comment by YongyuG** [comment]
> denoise_training_gao

some modification with vad, codes are the same as repo

**Comment by YongyuG** [comment]
> Is the denoise_gao.c file under bakcup2 the source for denoise_training_gao? Also, the count of the default denoise_training_gao is 80000000 x 75. Appreciate it if you could commit the denoise.c used for training. Thanks

sry for bag organized repo, backup repo is some experiments I did for myself, will clean it up

**Comment by wojiaohjhnihao** [comment]
> 您能提供denoise_training_gao的源代码吗？我想用新数据重新训练此模式。

同问我也想知道这个默认值是80000000我想自己设置可以吗，还有就是这个 denoise.c是不是有问题我想问，我生成的f32文件是有问题的是不是和数据集有关我的数据集音频时长都不一样而且都只有几秒，大小也对应不上如果是1000，大小是不是1000*75*4这样算，但实际生成的f32比这个大很多
