### ISSUE TITLE
When I cmake the project ,there is a problem

### ISSUE THREAD

**Issue by yangguo1112** [YongyuG/rnnoise_16k#6]
![2021-02-20 19-32-30屏幕截图](https://user-images.githubusercontent.com/51114294/108594871-74c1cf00-73b7-11eb-9901-afc020db4156.png)
Compiling according to your instructions shows an error as shown. I know little about compilation. Can you elaborate on your own compilation process for me,  thank you very much.

**Comment by yangguo1112** [comment]
If you are Chinese, you can speak in Chinese

**Comment by Ryuk17** [comment]
> ![2021-02-20 19-32-30屏幕截图](https://user-images.githubusercontent.com/51114294/108594871-74c1cf00-73b7-11eb-9901-afc020db4156.png)
> Compiling according to your instructions shows an error as shown. I know little about compilation. Can you elaborate on your own compilation process for me, thank you very much.

It seems that your VAD_GRU_SIZE, NOISE_GRU_SIZE may not be integer type.

**Comment by YongyuG** [comment]
Are you using window system?
If you have problem compiling it in LINUX, maybe you should delete CMakeCache.txt first
type :

  1.  cmake .

  1.  make

and done

________________________________
发件人: Ryuk ***@***.***>
发送时间: 2021年3月22日 6:44
收件人: YongyuG/rnnoise_16k ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [YongyuG/rnnoise_16k] When I cmake the project ,there is a problem (#6)


[2021-02-20 19-32-30屏幕截图]<https://user-images.githubusercontent.com/51114294/108594871-74c1cf00-73b7-11eb-9901-afc020db4156.png>
Compiling according to your instructions shows an error as shown. I know little about compilation. Can you elaborate on your own compilation process for me, thank you very much.

It seems that your VAD_GRU_SIZE, NOISE_GRU_SIZE may not be integer type.

―

**Comment by YongyuG** [comment]
你是windows系统吗?
windows的话我没验证,但是有terminal的话先把CMakeCache.txt删除.
然后cmake., make即可
________________________________
发件人: yangguo1112 ***@***.***>
发送时间: 2021年2月20日 12:22
收件人: YongyuG/rnnoise_16k ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [YongyuG/rnnoise_16k] When I cmake the project ,there is a problem (#6)


If you are Chinese, you can speak in Chinese

―
