### ISSUE TITLE
After the network model training is completed, about the problem of testing audio noise reduction

### ISSUE THREAD

**Issue by WangQin-wq** [YongyuG/rnnoise_16k#9]
I want to use noisy audio files to test the noise reduction effect of our trained model. How should we operate? I didn't see the relevant description. The source code of 48k is to put the input file before noise reduction and the output file after noise reduction into rnnoise_demo, 

.### /examples/rnnoise_demo <number of channels> <maximum attenuation> < input.raw > output.raw

but the file of rnnoise_demo is not seen in the 16k code. I hope the author can answer it. thank you @YongyuG

**Comment by YongyuG** [comment]
> I want to use noisy audio files to test the noise reduction effect of our trained model. How should we operate? I didn't see the relevant description. The source code of 48k is to put the input file before noise reduction and the output file after noise reduction into rnnoise_demo,
> 
> .### /examples/rnnoise_demo < input.raw > output.raw
> 
> but the file of rnnoise_demo is not seen in the 16k code. I hope the author can answer it. thank you @YongyuG

check the CMakeList.txt, the binary file will be generated which can help you to do the denoise things with your new trained models
